---
in_dir: "/home/user/wd/input"
out_dir: "/home/user/wd"
ref_sequence: "/home/user/iVar/res/FSS13025.fasta"
virus_map: "/home/user/iVar/res/zikvMap.csv"
script_locations: "/home/user/iVar/scripts"
replicates: [ "a", "b" ]

vco_test: 1
vco_pvalue: 0.05
vco_minFreq: 0.03

vca_compareWithReference: false
vca_minCoverage: 1
vca_minReads: 2
vca_minVarFreq: 0.01
vca_minAvgQual: 1
vca_pvalue: 0.97

tr_leading: 20
tr_trailing: 20
tr_sliding_window: "4:25"
tr_min_len: 30
tr_headcrop: 22

...
