---
in_dir: "/gpfs/home/natem/analysis/testing/input"
out_dir: "/gpfs/home/natem/analysis/testing"
ref_sequence: "/gpfs/home/natem/db/zikv/FSS13025.fasta"
virus_map: "/gpfs/home/natem/scripts/zika-pipeline/variant_calling/res/zikvMap.csv"
script_locations: "/gpfs/home/natem/scripts/zika-pipeline/variant_calling/scripts"
replicates: [ "a", "b" ]

vco_test: 1
vco_pvalue: 0.05
vco_minFreq: 0.03

vca_compareWithReference: false
vca_minCoverage: 1
vca_minReads: 2
vca_minVarFreq: 0.01
vca_minAvgQual: 1
vca_pvalue: 0.97

tr_leading: 20
tr_trailing: 20
tr_sliding_window: "4:25"
tr_min_len: 30
tr_headcrop: 2

...
